#!/bin/sh 

exec /usr/local/aolserver/bin/nsd-postgres -it /var/lib/aolserver/service0/etc/config.tcl -u service0 -g web

# For AOLserver 4 using privileged ports (usually < 1024), add the flag
# -b youraddress:yourport
